global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.50.2.186:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['3.208.152.85:9100','10.50.2.150:9100','10.50.2.126:9100','10.50.2.87:9100','10.50.2.41:9100','10.50.2.189:9100','10.50.2.186:9100']